### ISSUE TITLE
Some insane latency lag when running this

### ISSUE THREAD

**Issue by McFarts** [uglide/RedisDesktopManager#3572]
This thing absolutely bogs up your local network when running you cannot even stream anything, watch a youtube video or ANYTHING.

Any reason why it does this?  I've opened up my Redis db with other gui's but they're horrible.

I like this user interface the best, but I cannot even talk on skype with my buddy when  I have it running, what the fuck is it doing to my internal network may I ask?

**Comment by uglide** [comment]
Hi, I've never explored such issue and believe me,  I use RDM a lot. I need more info , provide Wireshark capturing damp please.

**Comment by McFarts** [comment]
Not sure if Wireshark will help.

But each capture was for 3-5 seconds and dumped:

This one is with RDM open:



This one is without:

**Comment by McFarts** [comment]
Not sure if Wireshark will help.

But each capture was for 3-5 seconds and dumped:

This one is with RDM open:

https://www.dropbox.com/s/3rz8gvai04kp2w9/latency.dmp.pcap?dl=0


This one is without:

https://www.dropbox.com/s/2uer78g9j16fq5m/latency2.dmp.pcapng?dl=0

**Comment by uglide** [comment]
Have check this dumps? In both dumps I see heavy UDP trafic between your PC and 108.61.218.146. So problem in your system and not in RDM.

**Comment by McFarts** [comment]
@uglide  Yeah, I saw that too.

It's just weird because when I have RDM open, the lag happens but when I close it, it doesn't. 

Not sure, but thanks for ur help

**Comment by McFarts** [comment]
@uglide  It is definitely RDM.

I just re-opened it again and my network latency / lag dropped significantly. 

There has to be a another way to check what's going on instead of a wireshark dump.

For example, using discourd or skype when I have the problem open the ping/latency indicator goes to red, then once i close RDM, goes right back to green.  Something is definitely going on.

**Comment by uglide** [comment]
@McFarts 
1. Which OS type/version do you use? 
2. Do you use SSH tunnel in RDM? 
3. How many opened connections in RDM do you have?

**Comment by McFarts** [comment]
1) Win 7 Pro 64-bit

2) Nope

3) 1, and my RDM server has only around 13mb of memory when running while working on my game / nodejs to add values to it.

This is the size of my db:
![](https://i.gyazo.com/f9b8a4a053ada5f5ce6a399d26ff0e35.png)

Like, it's just weird because right after I open the program I can notice the latency lag, but when I close it, everything is back to normal. It has to be the program, but I just don't know how to prove it to you, lol or find what's causing it :(

**Comment by uglide** [comment]
try to find out what causing UDP traffic, probably some malware starts to use network heavily when detects network activity from other apps

**Comment by lsrx** [comment]
Fabulous tool , but well, same problem here (Win 10 Pro, RDM 0.8.8.384).
I was wondering about a lagging and unresponsive system today and eventually found out that it was caused by RMD. Strangely it does not even has to be connected to my server (PuTTY-SSH-tunneled), just a running instance of it causes my network to be unresponsive for about 2-3 seconds every 5-6 seconds.

This is how it looks like if I ping redisdesktop.com:
![command_prompt_-_ping__-n_1000_redisdesktop com_2017-06-21_22-21-54](https://user-images.githubusercontent.com/10949281/27405369-9860de6c-56d1-11e7-99d2-4721caffc1f9.png)
 
And this with a running instance of RDM (not connected, just idling in the background):
![command_prompt_-_ping__-n_1000_redisdesktop com_2017-06-21_22-23-10](https://user-images.githubusercontent.com/10949281/27405468-eef00c58-56d1-11e7-8389-4c3b2f828893.png)

Same if I ping internal addresses. After closing, everything turns back to normal immediately.
Very strange behaviour.
